openapi: 3.0.3
info:
  title: Todo Application - Tasks API
  description: Task management endpoints for CRUD operations on user tasks
  version: 1.0.0
  contact:
    name: Todo App Team

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.todo-app.example.com
    description: Production server

tags:
  - name: Tasks
    description: Task management operations

security:
  - BearerAuth: []

paths:
  /api/tasks:
    get:
      tags:
        - Tasks
      summary: List all tasks for authenticated user
      description: Retrieve all tasks belonging to the authenticated user. Tasks are automatically filtered by user_id from JWT token.
      operationId: listTasks
      responses:
        '200':
          description: Tasks retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
              example:
                tasks:
                  - id: 1
                    user_id: 42
                    title: Buy groceries
                    description: Milk, eggs, bread
                    completed: false
                    created_at: '2026-02-05T10:00:00Z'
                    updated_at: '2026-02-05T10:00:00Z'
                  - id: 2
                    user_id: 42
                    title: Finish project report
                    description: null
                    completed: true
                    created_at: '2026-02-04T15:30:00Z'
                    updated_at: '2026-02-05T09:15:00Z'
        '401':
          description: Unauthorized (missing or invalid JWT)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Unauthorized
                details: Invalid or missing authentication token
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - Tasks
      summary: Create a new task
      description: Create a new task for the authenticated user. The user_id is automatically derived from the JWT token and should NOT be included in the request body.
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
            example:
              title: Buy groceries
              description: Milk, eggs, bread
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 1
                user_id: 42
                title: Buy groceries
                description: Milk, eggs, bread
                completed: false
                created_at: '2026-02-05T10:00:00Z'
                updated_at: '2026-02-05T10:00:00Z'
        '400':
          description: Invalid input (validation error)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                emptyTitle:
                  value:
                    error: Validation error
                    details: Title cannot be empty
                titleTooLong:
                  value:
                    error: Validation error
                    details: Title must be 500 characters or less
        '401':
          description: Unauthorized (missing or invalid JWT)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/tasks/{task_id}:
    get:
      tags:
        - Tasks
      summary: Get a specific task
      description: Retrieve a single task by ID. User can only access their own tasks (ownership verified via JWT).
      operationId: getTask
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: Task ID
          example: 1
      responses:
        '200':
          description: Task retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized (missing or invalid JWT)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found or does not belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Task not found
                details: Task with ID 1 does not exist or you do not have access
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      tags:
        - Tasks
      summary: Update a task
      description: Update an existing task. User can only update their own tasks (ownership verified via JWT). All fields are optional - only provided fields will be updated.
      operationId: updateTask
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: Task ID
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
            examples:
              toggleComplete:
                summary: Toggle completion status
                value:
                  completed: true
              updateTitle:
                summary: Update title only
                value:
                  title: Buy groceries and cook dinner
              updateAll:
                summary: Update all fields
                value:
                  title: Buy groceries and cook dinner
                  description: Milk, eggs, bread, chicken
                  completed: false
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 1
                user_id: 42
                title: Buy groceries and cook dinner
                description: Milk, eggs, bread, chicken
                completed: false
                created_at: '2026-02-05T10:00:00Z'
                updated_at: '2026-02-05T11:30:00Z'
        '400':
          description: Invalid input (validation error)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized (missing or invalid JWT)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found or does not belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      tags:
        - Tasks
      summary: Delete a task
      description: Permanently delete a task. User can only delete their own tasks (ownership verified via JWT). This operation cannot be undone.
      operationId: deleteTask
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: Task ID
          example: 1
      responses:
        '204':
          description: Task deleted successfully (no content)
        '401':
          description: Unauthorized (missing or invalid JWT)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found or does not belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          format: int64
          example: 1
          description: Unique task identifier
        user_id:
          type: integer
          format: int64
          example: 42
          description: ID of the user who owns this task
        title:
          type: string
          maxLength: 500
          example: Buy groceries
          description: Task title (required, max 500 characters)
        description:
          type: string
          nullable: true
          example: Milk, eggs, bread
          description: Task description (optional, no max length)
        completed:
          type: boolean
          example: false
          description: Whether the task is completed
        created_at:
          type: string
          format: date-time
          example: '2026-02-05T10:00:00Z'
          description: Timestamp when task was created (ISO 8601)
        updated_at:
          type: string
          format: date-time
          example: '2026-02-05T10:00:00Z'
          description: Timestamp when task was last updated (ISO 8601)
      description: Task object

    CreateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 500
          example: Buy groceries
          description: Task title (required, max 500 characters)
        description:
          type: string
          nullable: true
          example: Milk, eggs, bread
          description: Task description (optional)
      description: Request body for creating a new task (user_id is derived from JWT)

    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 500
          example: Buy groceries and cook dinner
          description: Updated task title (optional)
        description:
          type: string
          nullable: true
          example: Milk, eggs, bread, chicken
          description: Updated task description (optional)
        completed:
          type: boolean
          example: true
          description: Updated completion status (optional)
      description: Request body for updating a task (all fields optional, only provided fields are updated)

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: Task not found
          description: Human-readable error message
        details:
          type: string
          example: Task with ID 1 does not exist or you do not have access
          description: Additional error details (optional)
      description: Standard error response

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from /api/auth/signup or /api/auth/signin. Include in Authorization header as "Bearer <token>".

security:
  - BearerAuth: []
